const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.screenshot({path:'tests/desktop.png',fullPage:true});
await page.locator('[data-go="All comics"]').first().click();assert.equal(await page.locator('.comic-card').count(),8);
await page.locator('[data-comic="neon"]').first().click();for(let i=0;i<4;i++)await page.locator('.reader-controls .primary').click();assert.equal(await page.locator('.gate').count(),1);assert.match(await page.locator('.gate').innerText(),/4 free preview pages/);
await page.locator('[data-action="readerLogin"]').click();await page.locator('input[name="name"]').fill('Alex');await page.locator('input[name="email"]').fill('alex@example.com');await page.locator('#authForm .primary').click();assert.equal(await page.locator('.gate').count(),1);
await page.locator('.gate [data-action="subscribe"]').click();await page.locator('[data-checkout="membership"]').click();assert.equal(await page.locator('.comic-page').count(),1);await page.locator('.close').click();
await page.locator('[data-comic="sand"]').first().click();for(let i=0;i<4;i++)await page.locator('.reader-controls .primary').click();assert.match(await page.locator('.gate').innerText(),/not included with membership/);await page.locator('[data-buy="sand"]').click();await page.locator('[data-checkout="purchase"]').click();assert.equal(await page.locator('.comic-page').count(),1);await page.locator('.close').click();
await page.selectOption('#workspace','studio');await page.locator('[data-action="upload"]').first().click();await page.locator('[name="title"]').fill('Test publication');await page.locator('[name="synopsis"]').fill('A city beneath the sea.');await page.locator('[name="rights"]').check();await page.locator('button[value="submit"]').click();assert.match(await page.locator('.content').innerText(),/Test publication/);
await page.selectOption('#workspace','admin');await page.locator('[data-go="Review queue"]').click();await page.locator('tr').filter({hasText:'Test publication'}).locator('button').click();await page.locator('[name="checked"]').check();await page.locator('#reviewForm .primary').click();await page.screenshot({path:'tests/admin.png',fullPage:true});
await page.selectOption('#workspace','reader');await page.locator('[data-go="All comics"]').first().click();assert.equal(await page.locator('.comic-card').count(),9);await page.locator('#search').fill('Test publication');await page.locator('#search').press('Enter');assert.equal(await page.locator('.comic-card').count(),1);
await page.selectOption('#workspace','admin');await page.locator('[data-go="Content library"]').click();await page.locator('tr').filter({hasText:'Test publication'}).locator('button').click();await page.locator('#confirmVisibility').click();await page.selectOption('#workspace','reader');await page.locator('[data-go="All comics"]').first().click();assert.equal(await page.locator('.comic-card').count(),8);
for(const workspace of ['reader','studio','admin']){await page.selectOption('#workspace',workspace);const views=await page.locator('.nav-item[data-go]').evaluateAll(els=>els.map(e=>e.dataset.go));for(const view of views){await page.locator(`.nav-item[data-go="${view}"]`).click();assert.equal(await page.locator('h1').count(),1)}}
await page.selectOption('#workspace','reader');await page.evaluate(()=>localStorage.clear());await page.reload();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('.hero [data-comic]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'tests/mobile-reader.png',fullPage:true});assert.deepEqual(errors,[]);
const ctx2=await browser.newContext({viewport:{width:1280,height:900}});const guest=await ctx2.newPage();guest.on('pageerror',e=>errors.push(e.message));await guest.goto('http://127.0.0.1:4173');await guest.locator('[data-comic="forest"]').first().click();for(let i=0;i<4;i++)await guest.locator('.reader-controls .primary').click();assert.equal(await guest.locator('.gate').count(),1);await guest.locator('[data-action="readerLogin"]').click();await guest.locator('[name="name"]').fill('Free reader');await guest.locator('[name="email"]').fill('reader@example.com');await guest.locator('#authForm .primary').click();assert.equal(await guest.locator('.comic-page').count(),1);await guest.locator('[data-report="forest"]').click();await guest.locator('[name="detail"]').fill('Please check the age rating for this sample.');await guest.locator('#reportForm .primary').click();await guest.selectOption('#workspace','admin');assert.match(await guest.locator('.content').innerText(),/Please check the age rating/);await guest.locator('[data-resolve]').click();assert.equal(await guest.locator('[data-resolve]').count(),0);await guest.locator('[data-go="Authors & access"]').click();await guest.locator('[data-action="suspend"]').click();await guest.locator('#confirmSuspend').click();await guest.selectOption('#workspace','studio');await guest.locator('[data-action="upload"]').first().click();assert.match(await guest.locator('.modal').innerText(),/Publishing access is suspended/);await guest.locator('.close').click();await guest.setViewportSize({width:768,height:1024});assert.equal(await guest.locator('#workspace').isVisible(),true);await guest.setViewportSize({width:390,height:844});await guest.locator('[data-action="menu"]').click();await guest.selectOption('#workspace','admin');assert.match(await guest.locator('h1').innerText(),/healthy platform/);await ctx2.close();assert.deepEqual(errors,[]);
await browser.close();console.log('PASS: catalog, guest page gate, login gate, membership, purchase, author submission, admin approval, public publishing, unpublish, search, all workspace screens, mobile overflow, no browser errors.');})().catch(e=>{console.error(e);process.exit(1)});
